<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DapperDemo.View\DapperDemo.View.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Verion.Dominio.Infraestrutura" Version="19.0.1" />
    </ItemGroup>

</Project>
