<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
        One for Windows with net9.0-windows TFM, one for MacOS with net9.0-macos and one with net9.0 TFM for Linux.-->
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AssemblyName>DapperDemo.Desktop</AssemblyName>
        <RootNamespace>DapperDemo.Desktop</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DapperDemo.Infrastructure\DapperDemo.Infrastructure.csproj" />
    </ItemGroup>
</Project>

<!--        dotnet clean C:\Repos\Study\Projects\DapperDemo\DapperDemo\DapperDemo.sln -c Release-->

<!--        dotnet publish `-->
<!--        C:\Repos\Study\Projects\DapperDemo\DapperDemo\app\DapperDemo.Desktop\DapperDemo.Desktop.csproj `-->
<!--        -c Release `-->
<!--        -r win-x64 `-->
<!--        &#45;&#45;self-contained true `-->
<!--        -p:PublishSingleFile=true `-->
<!--        -p:IncludeNativeLibrariesForSelfExtract=true `-->
<!--        -p:EnableCompressionInSingleFile=true `-->
<!--        -p:DebugType=embedded `-->
<!--        -p:DebugSymbols=true `-->
<!--        -o C:\Repos\Study\Projects\DapperDemo\publish-->