<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
        One for Windows with net9.0-windows TFM, one for MacOS with net9.0-macos and one with net9.0 TFM for Linux.-->
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AssemblyName>Verion.Treinamento.DapperDemo.Desktop</AssemblyName>
        <RootNamespace>Verion.Treinamento.DapperDemo.Desktop</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Include="Verion.Infraestrutura.VerionNative.Core" Version="19.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DapperDemo.Infrastructure\DapperDemo.Infrastructure.csproj" />
    </ItemGroup>
</Project>
